-- ============================================================================
-- 10 - Seed: alerts, work orders, parts requirements
-- References turbines/sites/operatives/parts by their business codes so it is
-- independent of generated serial ids. Consistent with the attention set in 09.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Alerts
-- ---------------------------------------------------------------------------
INSERT INTO alerts (alert_time, severity, category, status, turbine_id, site_id, title, message, recommended_action)
VALUES
(now() - interval '2 hours',  'critical', 'sensor_anomaly', 'active',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'NSO-04'),
    (SELECT site_id FROM sites WHERE site_code = 'NSO'),
    'Turbine NSO-04 - vibration increase',
    'Main-shaft triaxial vibration trending up over the last 24h (X-axis RMS > 4.5 mm/s).',
    'Schedule bearing inspection within 10 days; verify against baseline.'),
(now() - interval '5 hours',  'critical', 'sensor_anomaly', 'active',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MTP-07'),
    (SELECT site_id FROM sites WHERE site_code = 'MTP'),
    'Turbine MTP-07 - bearing temperature rising',
    'Process temperature elevated and correlated with vibration. Possible early bearing degradation.',
    'Inspect main bearing; check lubrication.'),
(now() - interval '4 hours',  'warning',  'ml_prediction', 'active',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'CRG-03'),
    (SELECT site_id FROM sites WHERE site_code = 'CRG'),
    'Turbine CRG-03 - output below expected',
    'Predicted power output deviates from wind-adjusted expectation. Model flags early warning.',
    'Review pitch calibration and recent SCADA trend.'),
(now() - interval '8 hours',  'warning',  'maintenance_due', 'active',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'DFL-05'),
    (SELECT site_id FROM sites WHERE site_code = 'DFL'),
    'Turbine DFL-05 - maintenance window due',
    'Scheduled preventive maintenance interval reached.',
    'Plan preventive maintenance on a low-wind day.'),
(now() - interval '1 day',    'warning',  'maintenance_due', 'acknowledged',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MWP-11'),
    (SELECT site_id FROM sites WHERE site_code = 'MWP'),
    'Turbine MWP-11 - in maintenance',
    'Turbine taken offline for planned preventive maintenance.',
    'Complete work order and return to service.'),
(now() - interval '6 hours',  'critical', 'parts_shortage', 'active',
    NULL,
    (SELECT site_id FROM sites WHERE site_code = 'NSO'),
    'Low stock: main shaft bearing',
    'Main shaft bearing (BRG-MAIN-001) available quantity at/below reorder point with a 90-day lead time.',
    'Raise purchase order to avoid delaying corrective work.'),
(now() - interval '3 hours',  'info',     'weather_warning', 'active',
    NULL,
    (SELECT site_id FROM sites WHERE site_code = 'NSO'),
    'North Sea - high wind forecast',
    'Forecast wind above safe access limit (>15 m/s) over the next 36h.',
    'Defer offshore access; reschedule non-urgent work.');

-- ---------------------------------------------------------------------------
-- Work orders
-- ---------------------------------------------------------------------------
INSERT INTO work_orders (work_order_number, turbine_id, work_type, priority, status, title, description,
                         failure_mode, assigned_operative_id, assigned_date, scheduled_start, scheduled_end,
                         estimated_hours, predicted_failure_probability, ml_triggered, requires_low_wind, created_by)
VALUES
('WO-2026-000101',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'NSO-04'),
    'corrective', 'high', 'assigned',
    'NSO-04 main bearing inspection & likely replacement',
    'Vibration trend indicates bearing wear. Inspect and replace main shaft bearing if confirmed.',
    'OSF',
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-001'),
    now() - interval '2 hours', date_trunc('day', now()) + interval '3 days 7 hours', date_trunc('day', now()) + interval '5 days 15 hours',
    24.0, 0.78, TRUE, TRUE, 'pangea-ai'),
('WO-2026-000102',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MTP-07'),
    'inspection', 'high', 'assigned',
    'MTP-07 bearing temperature investigation',
    'Investigate rising bearing temperature; verify lubrication and sensor readings.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-004'),
    now() - interval '4 hours', date_trunc('day', now()) + interval '2 days 7 hours', date_trunc('day', now()) + interval '2 days 15 hours',
    8.0, 0.61, TRUE, TRUE, 'pangea-ai'),
('WO-2026-000103',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MWP-11'),
    'preventive', 'medium', 'in_progress',
    'MWP-11 scheduled gearbox oil change',
    'Routine gearbox lubrication oil replacement and filter change.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-008'),
    now() - interval '1 day', date_trunc('day', now()) + interval '7 hours', date_trunc('day', now()) + interval '15 hours',
    8.0, NULL, FALSE, FALSE, 'supervisor'),
('WO-2026-000104',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'DFL-05'),
    'preventive', 'low', 'scheduled',
    'DFL-05 preventive maintenance',
    'Scheduled preventive maintenance at interval.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-011'),
    NULL, date_trunc('day', now()) + interval '5 days 7 hours', date_trunc('day', now()) + interval '5 days 15 hours',
    8.0, NULL, FALSE, TRUE, 'supervisor'),
('WO-2026-000105',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'CRG-03'),
    'corrective', 'medium', 'scheduled',
    'CRG-03 pitch calibration',
    'Investigate output shortfall; recalibrate blade pitch.',
    'PWF',
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-005'),
    NULL, date_trunc('day', now()) + interval '4 days 7 hours', date_trunc('day', now()) + interval '4 days 15 hours',
    8.0, 0.44, TRUE, TRUE, 'pangea-ai'),
('WO-2026-000106',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'NSO-19'),
    'preventive', 'medium', 'completed',
    'NSO-19 blade inspection',
    'Completed routine blade inspection; no defects found.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-009'),
    now() - interval '9 days', date_trunc('day', now()) - interval '7 days' + interval '7 hours', date_trunc('day', now()) - interval '7 days' + interval '15 hours',
    8.0, NULL, FALSE, TRUE, 'supervisor'),
('WO-2026-000107',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'NSO-22'),
    'corrective', 'critical', 'assigned',
    'NSO-22 yaw drive fault',
    'Yaw drive not responding to control commands; nacelle stuck off-wind.',
    'OSF',
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-001'),
    now() - interval '6 hours', date_trunc('day', now()) + interval '1 days 7 hours', date_trunc('day', now()) + interval '1 days 15 hours',
    8.0, 0.88, TRUE, TRUE, 'pangea-ai'),
('WO-2026-000108',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MWP-06'),
    'inspection', 'medium', 'assigned',
    'MWP-06 annual generator inspection',
    'Annual generator winding and insulation resistance check.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-003'),
    now() - interval '1 day', date_trunc('day', now()) + interval '2 days 7 hours', date_trunc('day', now()) + interval '2 days 15 hours',
    8.0, NULL, FALSE, FALSE, 'supervisor'),
('WO-2026-000109',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'NSO-11'),
    'preventive', 'medium', 'in_progress',
    'NSO-11 offshore access platform check',
    'Inspect boat landing and access ladder before the autumn campaign.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-009'),
    now() - interval '2 days', date_trunc('day', now()) + interval '7 hours', date_trunc('day', now()) + interval '15 hours',
    8.0, NULL, FALSE, TRUE, 'supervisor'),
('WO-2026-000110',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MTP-14'),
    'corrective', 'high', 'assigned',
    'MTP-14 pitch hydraulic leak',
    'Hydraulic fluid loss detected on blade B pitch cylinder.',
    'PWF',
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-001'),
    now() - interval '3 hours', date_trunc('day', now()) + interval '6 days 7 hours', date_trunc('day', now()) + interval '6 days 15 hours',
    8.0, 0.66, TRUE, TRUE, 'pangea-ai'),
('WO-2026-000111',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'BJF-09'),
    'corrective', 'high', 'scheduled',
    'BJF-09 anemometer replacement',
    'Wind sensor reading inconsistently against neighbouring turbines. Needs an Arctic-rated technician.',
    NULL,
    NULL,
    NULL, date_trunc('day', now()) + interval '3 days 7 hours', date_trunc('day', now()) + interval '3 days 15 hours',
    8.0, 0.52, TRUE, TRUE, 'pangea-ai'),
('WO-2026-000112',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'CRG-14'),
    'inspection', 'medium', 'scheduled',
    'CRG-14 blade leading edge survey',
    'Rope access survey of leading edge erosion; requires rope-access certification.',
    NULL,
    NULL,
    NULL, date_trunc('day', now()) + interval '4 days 7 hours', date_trunc('day', now()) + interval '4 days 15 hours',
    8.0, NULL, FALSE, TRUE, 'supervisor'),
('WO-2026-000113',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'DFL-11'),
    'preventive', 'low', 'scheduled',
    'DFL-11 quarterly bolt torque check',
    'Routine tower flange bolt torque verification.',
    NULL,
    NULL,
    NULL, date_trunc('day', now()) + interval '8 days 7 hours', date_trunc('day', now()) + interval '8 days 15 hours',
    8.0, NULL, FALSE, TRUE, 'supervisor'),
('WO-2026-000114',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MWP-17'),
    'corrective', 'medium', 'on_hold',
    'MWP-17 converter cooling fan replacement',
    'Awaiting spare fan assembly from supplier.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-008'),
    now() - interval '5 days', date_trunc('day', now()) + interval '9 days 7 hours', date_trunc('day', now()) + interval '9 days 15 hours',
    8.0, NULL, FALSE, FALSE, 'supervisor');

-- ---------------------------------------------------------------------------
-- Routine backlog across the rest of the roster. Everyone in 07 gets work in
-- the next fortnight, at a site within reach of their base, so the schedule
-- calendar (/api/operators) shows a realistic load rather than a few outliers.
-- ---------------------------------------------------------------------------
INSERT INTO work_orders (work_order_number, turbine_id, work_type, priority, status, title, description,
                         failure_mode, assigned_operative_id, assigned_date, scheduled_start, scheduled_end,
                         estimated_hours, predicted_failure_probability, ml_triggered, requires_low_wind, created_by)
VALUES
('WO-2026-000115',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'CRG-07'),
    'corrective', 'high', 'assigned',
    'CRG-07 leading edge erosion repair',
    'Rope-access repair of blade A leading edge erosion found on the last survey.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-002'),
    now() - interval '1 day', date_trunc('day', now()) + interval '2 days 7 hours', date_trunc('day', now()) + interval '3 days 15 hours',
    16.0, NULL, FALSE, TRUE, 'supervisor'),
('WO-2026-000116',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'NSO-13'),
    'inspection', 'medium', 'assigned',
    'NSO-13 offshore blade inspection',
    'Autumn campaign blade inspection; vessel transfer from Esbjerg.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-002'),
    now() - interval '1 day', date_trunc('day', now()) + interval '9 days 7 hours', date_trunc('day', now()) + interval '9 days 15 hours',
    8.0, NULL, FALSE, TRUE, 'supervisor'),
('WO-2026-000117',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'CRG-09'),
    'corrective', 'high', 'assigned',
    'CRG-09 converter fault diagnosis',
    'Repeated converter trips under load. Diagnose and clear.',
    'RNF',
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-007'),
    now() - interval '5 hours', date_trunc('day', now()) + interval '1 days 7 hours', date_trunc('day', now()) + interval '1 days 15 hours',
    8.0, 0.58, TRUE, FALSE, 'pangea-ai'),
('WO-2026-000118',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'CRG-16'),
    'inspection', 'low', 'scheduled',
    'CRG-16 switchgear thermal inspection',
    'Thermographic survey of the tower base switchgear.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-007'),
    NULL, date_trunc('day', now()) + interval '7 days 7 hours', date_trunc('day', now()) + interval '7 days 15 hours',
    8.0, NULL, FALSE, FALSE, 'supervisor'),
('WO-2026-000119',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MTP-03'),
    'inspection', 'medium', 'assigned',
    'MTP-03 blade surface survey',
    'Rope-access survey after reported ice-throw damage last winter.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-010'),
    now() - interval '2 days', date_trunc('day', now()) + interval '4 days 7 hours', date_trunc('day', now()) + interval '4 days 15 hours',
    8.0, NULL, FALSE, TRUE, 'supervisor'),
('WO-2026-000120',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'CRG-02'),
    'corrective', 'medium', 'assigned',
    'CRG-02 pitch cylinder seal replacement',
    'Weeping seal on blade C pitch cylinder; replace with GBX-SEAL-014 kit.',
    'PWF',
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-012'),
    now() - interval '8 hours', date_trunc('day', now()) + interval '3 days 7 hours', date_trunc('day', now()) + interval '3 days 15 hours',
    8.0, 0.49, TRUE, TRUE, 'pangea-ai'),
('WO-2026-000121',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'CRG-11'),
    'preventive', 'low', 'scheduled',
    'CRG-11 hydraulic fluid service',
    'Scheduled hydraulic fluid replacement and filter change.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-012'),
    NULL, date_trunc('day', now()) + interval '10 days 7 hours', date_trunc('day', now()) + interval '10 days 15 hours',
    8.0, NULL, FALSE, FALSE, 'supervisor'),
('WO-2026-000122',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MWP-14'),
    'preventive', 'low', 'assigned',
    'MWP-14 vibration sensor replacement',
    'Swap the drifting triaxial sensor for a calibrated spare (SNS-VIB-003).',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-013'),
    now() - interval '1 day', date_trunc('day', now()) + interval '2 days 7 hours', date_trunc('day', now()) + interval '2 days 15 hours',
    8.0, NULL, FALSE, FALSE, 'supervisor'),
('WO-2026-000123',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MWP-03'),
    'preventive', 'low', 'scheduled',
    'MWP-03 nacelle filter change',
    'Routine nacelle air filter and cooling intake clean.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-013'),
    NULL, date_trunc('day', now()) + interval '6 days 7 hours', date_trunc('day', now()) + interval '6 days 15 hours',
    8.0, NULL, FALSE, FALSE, 'supervisor'),
('WO-2026-000124',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'DFL-08'),
    'preventive', 'low', 'assigned',
    'DFL-08 tower bolt torque check',
    'Quarterly tower flange bolt torque verification (FST-BLT-090).',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-014'),
    now() - interval '2 days', date_trunc('day', now()) + interval '1 days 7 hours', date_trunc('day', now()) + interval '1 days 15 hours',
    8.0, NULL, FALSE, TRUE, 'supervisor'),
('WO-2026-000125',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MTP-11'),
    'preventive', 'low', 'assigned',
    'MTP-11 yaw gear lubrication service',
    'Grease yaw ring and inspect yaw drive motor mounting.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-015'),
    now() - interval '1 day', date_trunc('day', now()) + interval '2 days 7 hours', date_trunc('day', now()) + interval '2 days 15 hours',
    8.0, NULL, FALSE, FALSE, 'supervisor'),
('WO-2026-000126',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'DFL-02'),
    'inspection', 'medium', 'scheduled',
    'DFL-02 gearbox oil analysis follow-up',
    'Particle count was elevated in the last sample. Re-sample and inspect filter.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-006'),
    NULL, date_trunc('day', now()) + interval '3 days 7 hours', date_trunc('day', now()) + interval '3 days 15 hours',
    8.0, NULL, FALSE, FALSE, 'supervisor'),
('WO-2026-000127',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'NSO-16'),
    'inspection', 'medium', 'assigned',
    'NSO-16 generator winding resistance check',
    'Insulation resistance and winding temperature sensor verification.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-009'),
    now() - interval '3 days', date_trunc('day', now()) + interval '7 days 7 hours', date_trunc('day', now()) + interval '7 days 15 hours',
    8.0, NULL, FALSE, TRUE, 'supervisor'),
('WO-2026-000128',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MWP-08'),
    'inspection', 'medium', 'scheduled',
    'MWP-08 HV switchgear survey',
    'High-voltage switchgear condition survey; requires HV certification.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-003'),
    NULL, date_trunc('day', now()) + interval '11 days 7 hours', date_trunc('day', now()) + interval '11 days 15 hours',
    8.0, NULL, FALSE, FALSE, 'supervisor'),
('WO-2026-000129',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'NSO-08'),
    'corrective', 'high', 'scheduled',
    'NSO-08 blade leading edge repair',
    'Composite repair of leading edge erosion (BLD-REP-050); weather window needed.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-005'),
    NULL, date_trunc('day', now()) + interval '11 days 7 hours', date_trunc('day', now()) + interval '12 days 15 hours',
    16.0, 0.41, TRUE, TRUE, 'pangea-ai'),
('WO-2026-000130',
    (SELECT turbine_id FROM turbines WHERE turbine_code = 'MTP-09'),
    'preventive', 'medium', 'scheduled',
    'MTP-09 pitch accumulator recharge',
    'Nitrogen pre-charge check and top-up on all three pitch accumulators.',
    NULL,
    (SELECT operative_id FROM maintenance_operatives WHERE employee_code = 'OP-004'),
    NULL, date_trunc('day', now()) + interval '12 days 7 hours', date_trunc('day', now()) + interval '12 days 15 hours',
    8.0, NULL, FALSE, FALSE, 'supervisor');

-- The dates above are targets. Which weekday they land on depends on when the
-- chart is installed, so snap every job onto a shift its operative actually
-- works: right day, right start hour, no two jobs on one person at once.
SELECT reflow_assignments();

-- ---------------------------------------------------------------------------
-- Parts requirements (parts needed per work order)
-- ---------------------------------------------------------------------------
INSERT INTO parts_requirements (work_order_id, part_id, quantity_required, quantity_allocated, notes)
VALUES
((SELECT work_order_id FROM work_orders WHERE work_order_number = 'WO-2026-000101'),
 (SELECT part_id FROM parts_inventory WHERE part_number = 'BRG-MAIN-001'), 1, 1, 'Reserve main bearing for corrective work.'),
((SELECT work_order_id FROM work_orders WHERE work_order_number = 'WO-2026-000102'),
 (SELECT part_id FROM parts_inventory WHERE part_number = 'SNS-VIB-003'), 2, 2, 'Replace suspect vibration sensors.'),
((SELECT work_order_id FROM work_orders WHERE work_order_number = 'WO-2026-000103'),
 (SELECT part_id FROM parts_inventory WHERE part_number = 'LUB-OIL-031'), 2, 2, 'Gearbox oil.'),
((SELECT work_order_id FROM work_orders WHERE work_order_number = 'WO-2026-000103'),
 (SELECT part_id FROM parts_inventory WHERE part_number = 'GBX-SEAL-014'), 1, 1, 'Seal kit for oil change.'),
((SELECT work_order_id FROM work_orders WHERE work_order_number = 'WO-2026-000120'),
 (SELECT part_id FROM parts_inventory WHERE part_number = 'GBX-SEAL-014'), 1, 1, 'Pitch cylinder seal.'),
((SELECT work_order_id FROM work_orders WHERE work_order_number = 'WO-2026-000121'),
 (SELECT part_id FROM parts_inventory WHERE part_number = 'HYD-FLD-030'), 1, 0, 'Not yet picked; order is still scheduled.'),
((SELECT work_order_id FROM work_orders WHERE work_order_number = 'WO-2026-000122'),
 (SELECT part_id FROM parts_inventory WHERE part_number = 'SNS-VIB-003'), 1, 1, 'Calibrated replacement sensor.'),
((SELECT work_order_id FROM work_orders WHERE work_order_number = 'WO-2026-000124'),
 (SELECT part_id FROM parts_inventory WHERE part_number = 'FST-BLT-090'), 1, 1, 'Replacement bolts for any found below torque.'),
((SELECT work_order_id FROM work_orders WHERE work_order_number = 'WO-2026-000129'),
 (SELECT part_id FROM parts_inventory WHERE part_number = 'BLD-REP-050'), 1, 0, 'Not yet picked; awaiting a weather window.');
