apiVersion: v1
kind: Secret
metadata:
  name: pangea-db-credentials
  labels:
    app.kubernetes.io/name: pangea-db
    app.kubernetes.io/part-of: pangea-power
type: Opaque
stringData:
  database-name: {{ .Values.credentials.database | quote }}
  database-user: {{ .Values.credentials.user | quote }}
  database-password: {{ .Values.credentials.password | quote }}
