apiVersion: v1
kind: Service
metadata:
  name: pangea-db
  labels:
    app.kubernetes.io/name: pangea-db
    app.kubernetes.io/part-of: pangea-power
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app.kubernetes.io/name: pangea-db
