FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

# Patch base-image packages to pick up the latest CVE fixes.
RUN microdnf update -y && microdnf clean all

COPY config.json generation_config.json model.safetensors \
     tokenizer.json tokenizer_config.json vocab.json merges.txt \
     special_tokens_map.json chat_template.jinja /models/

USER 1001
