apiVersion: v1
kind: ServiceAccount
metadata:
  name: pangea-mlflow
  labels:
    app.kubernetes.io/name: pangea-api
---
apiVersion: v1
kind: Secret
metadata:
  name: pangea-mlflow-token
  labels:
    app.kubernetes.io/name: pangea-api
  annotations:
    kubernetes.io/service-account.name: pangea-mlflow
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pangea-mlflow-admin
  labels:
    app.kubernetes.io/name: pangea-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: pangea-mlflow
