apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: laya-predictor
  annotations:
    serving.kserve.io/deploymentMode: Standard
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
spec:
  predictor:
    model:
      modelFormat:
        name: laya
      runtime: laya-typed-decisions
